spring:
  application:
    name: fastsns

  datasource:
    url: jdbc:mysql://localhost:3306/fast_sns?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: localpw

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379